language: python
python:
    - "2.7"
    - "3.6"
    - "3.7"
    - "3.8"
install:
    - "pip install coverage"
    - "pip install coveralls"
script:
    - "coverage run --source=luhn setup.py test"
after_success:
    coveralls
